### ISSUE TITLE
sublimetext - vale-ls: thread 'main' panicked

### ISSUE THREAD

**Issue by aireilly** [errata-ai/vale-ls#13]
Fedora Linux 39 (Workstation Edition)
Linux 6.8.11-200.fc39.x86_64
Sublime version 4175

vale-ls suddenly stopped working. I have tried installing and reinstalling, nothing seems to work. Vale-ls does not lint in the Sublime editor.

I see errors like this in the LSP log:
```
:: [11:21:21.735] --> vale-ls initialize (1): {'processId': 28627, 'clientInfo': {'name': 'Sublime Text LSP', 'version': '2.1.0'}, 'rootUri': 'file://home/aireilly/openshift-docs', 'rootPath': '//home/aireilly/openshift-docs', 'workspaceFolders': [{'name': 'openshift-docs', 'uri': 'file://home/aireilly/openshift-docs'}], 'capabilities': {'general': {'regularExpressions': {'engine': 'ECMAScript'}, 'markdown': {'parser': 'Python-Markdown', 'version': '3.2.2'}}, 'textDocument': {'synchronization': {'dynamicRegistration': True, 'didSave': True, 'willSave': True, 'willSaveWaitUntil': True}, 'hover': {'dynamicRegistration': True, 'contentFormat': [<MarkupKind.Markdown: 'markdown'>, <MarkupKind.PlainText: 'plaintext'>]}, 'completion': {'dynamicRegistration': True, 'completionItem': {'snippetSupport': True, 'deprecatedSupport': True, 'documentationFormat': [<MarkupKind.Markdown: 'markdown'>, <MarkupKind.PlainText: 'plaintext'>], 'tagSupport': {'valueSet': [1]}, 'resolveSupport': {'properties': ['detail', 'documentation', 'additionalTextEdits']}, 'insertReplaceSupport': True, 'insertTextModeSupport': {'valueSet': [2]}, 'labelDetailsSupport': True}, 'completionItemKind': {'valueSet': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]}, 'insertTextMode': 2, 'completionList': {'itemDefaults': ['editRange', 'insertTextFormat', 'data']}}, 'signatureHelp': {'dynamicRegistration': True, 'contextSupport': True, 'signatureInformation': {'activeParameterSupport': True, 'documentationFormat': [<MarkupKind.Markdown: 'markdown'>, <MarkupKind.PlainText: 'plaintext'>], 'parameterInformation': {'labelOffsetSupport': True}}}, 'references': {'dynamicRegistration': True}, 'documentHighlight': {'dynamicRegistration': True}, 'documentSymbol': {'dynamicRegistration': True, 'hierarchicalDocumentSymbolSupport': True, 'symbolKind': {'valueSet': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]}, 'tagSupport': {'valueSet': [1]}}, 'documentLink': {'dynamicRegistration': True, 'tooltipSupport': True}, 'formatting': {'dynamicRegistration': True}, 'rangeFormatting': {'dynamicRegistration': True, 'rangesSupport': True}, 'declaration': {'dynamicRegistration': True, 'linkSupport': True}, 'definition': {'dynamicRegistration': True, 'linkSupport': True}, 'typeDefinition': {'dynamicRegistration': True, 'linkSupport': True}, 'implementation': {'dynamicRegistration': True, 'linkSupport': True}, 'codeAction': {'dynamicRegistration': True, 'codeActionLiteralSupport': {'codeActionKind': {'valueSet': [<CodeActionKind.QuickFix: 'quickfix'>, <CodeActionKind.Refactor: 'refactor'>, <CodeActionKind.RefactorExtract: 'refactor.extract'>, <CodeActionKind.RefactorInline: 'refactor.inline'>, <CodeActionKind.RefactorRewrite: 'refactor.rewrite'>, <CodeActionKind.SourceFixAll: 'source.fixAll'>, <CodeActionKind.SourceOrganizeImports: 'source.organizeImports'>]}}, 'dataSupport': True, 'isPreferredSupport': True, 'resolveSupport': {'properties': ['edit']}}, 'rename': {'dynamicRegistration': True, 'prepareSupport': True, 'prepareSupportDefaultBehavior': 1}, 'colorProvider': {'dynamicRegistration': True}, 'publishDiagnostics': {'relatedInformation': True, 'tagSupport': {'valueSet': [1, 2]}, 'versionSupport': True, 'codeDescriptionSupport': True, 'dataSupport': True}, 'diagnostic': {'dynamicRegistration': True, 'relatedDocumentSupport': True}, 'selectionRange': {'dynamicRegistration': True}, 'foldingRange': {'dynamicRegistration': True, 'foldingRangeKind': {'valueSet': [<FoldingRangeKind.Comment: 'comment'>, <FoldingRangeKind.Imports: 'imports'>, <FoldingRangeKind.Region: 'region'>]}}, 'codeLens': {'dynamicRegistration': True}, 'inlayHint': {'dynamicRegistration': True, 'resolveSupport': {'properties': ['textEdits', 'label.command']}}, 'semanticTokens': {'dynamicRegistration': True, 'requests': {'range': True, 'full': {'delta': True}}, 'tokenTypes': [<SemanticTokenTypes.Namespace: 'namespace'>, <SemanticTokenTypes.Type: 'type'>, <SemanticTokenTypes.Class: 'class'>, <SemanticTokenTypes.Enum: 'enum'>, <SemanticTokenTypes.Interface: 'interface'>, <SemanticTokenTypes.Struct: 'struct'>, <SemanticTokenTypes.TypeParameter: 'typeParameter'>, <SemanticTokenTypes.Parameter: 'parameter'>, <SemanticTokenTypes.Variable: 'variable'>, <SemanticTokenTypes.Property: 'property'>, <SemanticTokenTypes.EnumMember: 'enumMember'>, <SemanticTokenTypes.Event: 'event'>, <SemanticTokenTypes.Function: 'function'>, <SemanticTokenTypes.Method: 'method'>, <SemanticTokenTypes.Macro: 'macro'>, <SemanticTokenTypes.Keyword: 'keyword'>, <SemanticTokenTypes.Modifier: 'modifier'>, <SemanticTokenTypes.Comment: 'comment'>, <SemanticTokenTypes.String: 'string'>, <SemanticTokenTypes.Number: 'number'>, <SemanticTokenTypes.Regexp: 'regexp'>, <SemanticTokenTypes.Operator: 'operator'>, <SemanticTokenTypes.Decorator: 'decorator'>], 'tokenModifiers': [<SemanticTokenModifiers.Declaration: 'declaration'>, <SemanticTokenModifiers.Definition: 'definition'>, <SemanticTokenModifiers.Readonly: 'readonly'>, <SemanticTokenModifiers.Static: 'static'>, <SemanticTokenModifiers.Deprecated: 'deprecated'>, <SemanticTokenModifiers.Abstract: 'abstract'>, <SemanticTokenModifiers.Async: 'async'>, <SemanticTokenModifiers.Modification: 'modification'>, <SemanticTokenModifiers.Documentation: 'documentation'>, <SemanticTokenModifiers.DefaultLibrary: 'defaultLibrary'>], 'formats': [<TokenFormat.Relative: 'relative'>], 'overlappingTokenSupport': False, 'multilineTokenSupport': True, 'augmentsSyntaxTokens': True}, 'callHierarchy': {'dynamicRegistration': True}, 'typeHierarchy': {'dynamicRegistration': True}}, 'workspace': {'applyEdit': True, 'didChangeConfiguration': {'dynamicRegistration': True}, 'executeCommand': {}, 'workspaceEdit': {'documentChanges': True, 'failureHandling': <FailureHandlingKind.Abort: 'abort'>}, 'workspaceFolders': True, 'symbol': {'dynamicRegistration': True, 'resolveSupport': {'properties': ['location.range']}, 'symbolKind': {'valueSet': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]}, 'tagSupport': {'valueSet': [1]}}, 'configuration': True, 'codeLens': {'refreshSupport': True}, 'inlayHint': {'refreshSupport': True}, 'semanticTokens': {'refreshSupport': True}, 'diagnostics': {'refreshSupport': True}}, 'window': {'showDocument': {'support': True}, 'showMessage': {'messageActionItem': {'additionalPropertiesSupport': True}}, 'workDoneProgress': True}}, 'initializationOptions': {'RUST_BACKTRACE': 1, 'configPath': '', 'filter': '', 'installVale': True, 'syncOnStartup': True}}

vale-ls: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', src/server.rs:38:18
vale-ls: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

# Server diagnostics

# Troubleshooting: vale-ls
## Version
 - LSP: 2.1.0
 - Sublime Text: 4175
## Server Test Run
 - exit code: 0
 - output
```

```
## Server Configuration
 - command
```json
[
  "${storage_path}/LSP-vale-ls/vale-ls"
]
```
 - shell command
```sh
"/home/aireilly/.cache/sublime-text/Package Storage/LSP-vale-ls/vale-ls"
```
 - selector
```
source.ini | source.yaml | text.html.markdown | text.restructuredtext | text.asciidoc
```
 - priority_selector
```
source.ini | source.yaml | text.html.markdown | text.restructuredtext | text.asciidoc
```
 - init_options
```json
{
  "RUST_BACKTRACE": 1,
  "configPath": "",
  "filter": "",
  "installVale": true,
  "syncOnStartup": true
}
```
 - settings
```json
{}
```
 - env
```json
{}
```

## Active view
 - File name
```
//home/aireilly/openshift-docs/edge_computing/ztp-advanced-install-ztp.adoc
```
 - Settings
```json
{
  "auto_complete_selector": "meta.tag, source - comment - string.quoted.double.block - string.quoted.single.block - string.unquoted.heredoc",
  "lsp_active": null,
  "syntax": "Packages/ST3-Asciidoctor/Syntaxes/Asciidoctor.sublime-syntax"
}
```
 - base scope
```
text.asciidoc
```

## Project / Workspace
 - folders
```json
[
  "//home/aireilly/openshift-docs"
]
```
 - is project: True
 - project data:
```json
{
  "folders": [
    {
      "follow_symlinks": false,
      "path": "."
    }
  ],
  "settings": {
    "source_folder": "."
  }
}
```

## LSP configuration

```json
{
  "clients": {},
  "diagnostics_gutter_marker": "circle",
  "diagnostics_highlight_style": {
    "error": "squiggly",
    "hint": "squiggly",
    "info": "stippled",
    "warning": "squiggly"
  },
  "log_debug": true,
  "lsp_format_on_save": false,
  "show_code_lens": "annotation",
  "show_diagnostics_panel_on_save": 0
}
```
## System PATH
 - /home/aireilly/.nvm/versions/node/v20.9.0/bin
 - /home/aireilly/.local/bin
 - /usr/local/bin
 - /home/aireilly/bin
 - /usr/local/bin
 - /usr/local/sbin
 - /usr/bin
 - /usr/sbin
 - /home/aireilly/bin/dita-ot-4.2.3/bin
 - /usr/local/go/bin
 - /home/aireilly/.rvm/bin

**Comment by aireilly** [comment]
Fixed after reinstalling LSP-vale-ls :shrug:

**Comment by aireilly** [comment]
No there is definitely something up with vale-ls. I get crashes like this in the console: 

```
vale-ls: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', src/server.rs:38:18
vale-ls: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by jdkato** [comment]
Should be fixed in the next release.

**Comment by aireilly** [comment]
Fantastic thanks.
